from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline #1. It is used to create a chat model using a Hugging Face pipeline.


llm= HuggingFacePipeline.from_model_id(#2. It initializes a Hugging Face pipeline using a specific model ID and task.
    model_id="TinyLlama/TinyLlama-1.1B-Chat-v1.0",#It specifies the model ID from Hugging Face to be used for the chat model.
    task="text-generation", #It indicates that the task for the model is text generation.
    pipeline_kwargs=dict(
        temperature =0.5, 
        max_new_tokens= 512
    )#It sets additional parameters for the text generation pipeline, such as temperature and maximum number of new tokens to generate.
),

model = ChatHuggingFace(llm=llm)


result = model.invoke("What is the national sport of India?")#3. It invokes the chat model with a prompt asking for the national spot of India.

print(result.content) #4. It prints the content of the response generated by the chat model.


#When you run this enire code, it will output the national sport of India based on the response from the TinyLlama model.
#Also it will download the model locally if not already present.